### PR TITLE
Added sorted linked list implementation

### PR DESCRIPTION
**Pull request by korken89**
A linked list priority queue, similar to binary heap.
Has different useful properties.

### CODE REVIEW

**Comment by Dirbaio** [comment]
Name should maybe be `SortedLinkedList`? I would expect `LinkedList` to be the good old linked list where the user is in control of the order.

**Comment by korken89** [comment]
@Dirbaio I see your point, but this not done for the binary heap, so I think the name as it is is proper. Maybe you had a different issue with the name in mind?
I can also expand on the module documentation.

One can also get a non sorted list by implementing Ord to equal the Ordering of Min/Max, though a bit cumbersome. :)

**Comment by Dirbaio** [comment]
binary heaps are "sorted" by definition (as in a node is greater/smaller than its children), so the name "sorted binary heap" would be redundant. Linked lists aren't: you put things in and they stay in the order you put them in. This is a linked list that additionally sorts itself, hence SortedLinkedList :)

**Comment by korken89** [comment]
@Dirbaio Good point! I changed name.

**Review by perlindgren — APPROVED** [review]
Overall structure and safety assessments look good. Minor details have been confirmed with @korken89 during the review.

**Comment by korken89** [comment]
Thanks for the review!

**Pull request merged**
