### PR TITLE
v0.2.0

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9d82107 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9d8210761c9d8df031cd2c4500d1a6ac250ca715 with merge 5b91d6821aa4630e6ddec13640d1336b089942fa...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/heapless/builds/305984028?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 5b91d6821aa4630e6ddec13640d1336b089942fa to master...

**Pull request merged**
