### PR TITLE
First GitHub Actions test

### PR DESCRIPTION
**Pull request by AfoHT**
The test named `testtsan` fails with a 

```
WARNING: ThreadSanitizer: data race (pid=2180)
```

This seems to be a known issue? What would you suggest?

### CODE REVIEW

**Comment by korken89** [comment]
Thanks for the PR!

Ping @japaric on the test, I've tried to reproduce locally but to no avail so if you can have a look it would be great!
Else I'll remove the test.

**Comment by japaric** [comment]
I can't repro the failure locally with ~nightly-2020-10-24. Is that test blocking CI? I don't see any GitHub Actions run in this repo.

**Comment by AfoHT** [comment]
Not sure why GHA doesn't detect the incoming GHA changes and try them directly, could be a special case with this being the introduction/enabling of GHA.

On my fork the result can be seen: [GHA test heapless](https://github.com/AfoHT/heapless/runs/1494991538?check_suite_focus=true)

The style/cargo fmt failure is fixed already.

**Comment by korken89** [comment]
@japaric Yeah none of us are able to reproduce it, I have even tried different nightlies.
Not sure how to proceed with it. But if we can't reproduce, I'll remove that test for the time being.

**Comment by japaric** [comment]
>  Yeah none of us are able to reproduce it, I have even tried different nightlies.

Yesterday, I had a GHA build failed because I set `CARGO_TERM_COLOR=always`. I doubt that's the case here though.

> On my fork the result can be seen: GHA test heapless

That's hard to read. I would suggest passing `--test-threads=1` to the `cargo test --test tsan --target=x86_64-unknown-linux-gnu --features=x86-sync-pool` command to make it easier (I hope) to spot which test is triggering the sanitizer error.

**Comment by AfoHT** [comment]
How interesting! See [GHA Run](https://github.com/AfoHT/heapless/actions/runs/413625347)

By adding `test-threads=1` the test magically fixed itself, now everything is green :heavy_check_mark:

**Comment by japaric** [comment]
> By adding test-threads=1 the test magically fixed itself, now everything is green 

then it may have been a false positive in the (standard library) test runner. The heapless unit tests don't share share heapless data structures between them (as far as I remember)

**Comment by korken89** [comment]
Then it seems fine, lets merge this!

**Comment by korken89** [comment]
Is there anything you feel is missing from this PR @AfoHT ? Else I'll merge it :)
Great work!

**Review by korken89 — APPROVED** [review]

**Pull request merged**
