### PR TITLE
add BinaryHeap::into_vec

### PR DESCRIPTION
**Pull request by Lambda-Logan**
std::collections::BinaryHeap provides an into_vec method https://doc.rust-lang.org/std/collections/struct.BinaryHeap.html#method.into_vec

My use case is I want a sorted iterator  similar to BinaryHeap.into_sorted_iter. I found my self creating a new heapless:Vec from heapless::BinaryHeap::into_iter and then sorting it. It seemed better to return the underlying vec and sort that.

But the functionality seemed generally useful and helps the API jive a little better with std::collections::BinaryHeap.

Do you see any issues with this implementation? Also, apologies for anything weird... This is my first PR :)

### CODE REVIEW

**Comment by japaric** [comment]
thanks for the PR! sorry that it felt through the cracks :-(

turns out there was a bug in the BinaryHeap implementation and it was dropping the elements twice. that was fixed in PR #287

with that change the implementation of `into_vec` should be the same as of the one in the standard library: `self.data` with any addition of `ManuallyDrop`

could you update the implementation? the current one is not running destructors after the change in PR #287

**Comment by Lambda-Logan** [comment]
@japaric  Like this?

**Review by japaric — APPROVED** [review]
yes, thanks!

**Comment by japaric** [comment]
release v0.7.13 includes this change

**Pull request merged**
