### PR TITLE
use atomics where available

### PR DESCRIPTION
**Pull request by japaric**
cc #5
cc @pftbest

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit f9a3dfcc891605e8a8dbb5bb2ccbe24bd7b6b775 with merge 4a527afe400410ac11c7a782a8ce033ce56abb58...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/heapless/builds/295486744?utm_source=github_status&utm_medium=notification)
State: approved= try=True

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 158d19b45a12077a180f8507c1407af3076fd2b5 with merge b519403be9eddfa3bc9691e9e8d098d3c57e797d...

**Comment by japaric** [comment]
> SUMMARY: ThreadSanitizer: data race /checkout/src/liballoc/heap.rs:104 in _$LT$alloc..heap..Heap$u20$as$u20$alloc..allocator..Alloc$GT$::dealloc::h42931c7bdbec6994

Hmm, looks like the Travis environment doesn't do demangling for some reason.

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/heapless/builds/295488311?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit a93f8570dc7ef90a468dfe348970d8b6fcb182ea with merge 5fcb8c44ed9547ff0459759306a4e8e5f06fdcd5...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/heapless/builds/295498878?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
I tested running the sanitizer on a minimal Ubuntu 16.04 install and demangling works there. Then I remembered that Travis is using 14.04, which I haven't tested.

**Comment by pftbest** [comment]
> All single core systems are supported.

I think this statement might be not exactly true. There are some single core systems that can execute instructions out-of-order, and can break this code.

Good news is that Cortex-M is [not one of them](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dai0321a/BIHJIIIC.html) yet:

> The Cortex-M processors never perform memory accesses out of order compared to instruction flow, however, the architecture does not prohibit this in future implementations. ARMv7-M code written to be portable to ARMv7-AR processors, like Cortex-A9, must already take account of this ordering model.

I believe that such platforms like Cortex-A9 all have atomic support, so this wouldn't matter in practice, but running non-atomic code on them would probably be a mistake, even if they have only one core.

**Comment by japaric** [comment]
Good point, @pftbest. I think we should note that (out-of-order execution) in the documentation. I think it's best to ask the user to check the disassembly if they are using a single core system with "no atomics"; if the code is wrong the fix will involve patching the implementation for that specific architecture / target (i.e. `#[cfg]`) as I don't think there's a general way to insert instruction / memory barriers via LLVM intrinsics.

**Comment by japaric** [comment]
I ended up re-implementing `AtomicUsize` using atomic load/store (LLVM) intrinsics. This way I was able to drop the conditional code while retaining support for thumbv6m-none-eabi.

**Comment by pftbest** [comment]
That's a great idea.

**Comment by japaric** [comment]
I changed the `load_acquire` for `load_relaxed`. The previous version produced *two* memory barriers; I think we only need *one*: the one between the data read / write and the the head / tail pointer update.

So, this code:

``` rust
fn exti0() {
    unsafe {
        RB.split().0.enqueue(0).unwrap();
    }
}
```

Produced:

``` armasm
080001c0 <EXTI0>:
 80001c0:       f240 0000       movw    r0, #0
 80001c4:       f2c2 0000       movt    r0, #8192       ; 0x2000
 80001c8:       6803            ldr     r3, [r0, #0]
 80001ca:       6842            ldr     r2, [r0, #4]
 80001cc:       f3bf 8f5f       dmb     sy
 80001d0:       1c51            adds    r1, r2, #1
 80001d2:       f001 010f       and.w   r1, r1, #15
 80001d6:       4299            cmp     r1, r3
 80001d8:       bf1f            itttt   ne
 80001da:       eb00 0282       addne.w r2, r0, r2, lsl #2
 80001de:       2300            movne   r3, #0
 80001e0:       6093            strne   r3, [r2, #8]
 80001e2:       f3bf 8f5f       dmbne   sy
 80001e6:       bf1c            itt     ne
 80001e8:       6041            strne   r1, [r0, #4]
 80001ea:       4770            bxne    lr
 80001ec:       b580            push    {r7, lr}
 80001ee:       466f            mov     r7, sp
 80001f0:       f7ff ffe2       bl      80001b8 <core::result::unwrap_failed>
```

With the change, it now produces:

``` armasm
080001f0 <EXTI0>:
 80001f0:       f240 0000       movw    r0, #0
 80001f4:       f2c2 0000       movt    r0, #8192       ; 0x2000
 80001f8:       6803            ldr     r3, [r0, #0]
 80001fa:       6842            ldr     r2, [r0, #4]
 80001fc:       1c51            adds    r1, r2, #1
 80001fe:       f001 010f       and.w   r1, r1, #15
 8000202:       4299            cmp     r1, r3
 8000204:       bf1f            itttt   ne
 8000206:       eb00 0282       addne.w r2, r0, r2, lsl #2
 800020a:       2300            movne   r3, #0
 800020c:       6093            strne   r3, [r2, #8]
 800020e:       f3bf 8f5f       dmbne   sy
 8000212:       bf1c            itt     ne
 8000214:       6041            strne   r1, [r0, #4]
 8000216:       4770            bxne    lr
 8000218:       b580            push    {r7, lr}
 800021a:       466f            mov     r7, sp
 800021c:       f7ff ffcc       bl      80001b8 <core::result::unwrap_failed>
```

TSan seems to be OK with the change.

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit af5fdf38d59342c1d9060b42e75bafe730d80daa with merge b31015c4201ffc00361f6edc0ed8cfd19b1312ba...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/heapless/builds/299366674?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 7806bc9169074680dd22b8e0d07d82a7bc1eab31 with merge 14a5689cc74e8d5e5769d92185967eefae16c713...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/heapless/builds/299372934?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 5ff961c3ad0a41c577bfcdb3f8c904414bcbabb5 with merge 89e5733113cfd849bbb5c6539df52bf4f5ca5304...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/heapless/builds/299399092?utm_source=github_status&utm_medium=notification)
State: approved= try=True

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 30ea33c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 30ea33c349f44c1903ae8302341f7aa37614dddb with merge 612bf44a78c436db7d8aab83d0b65fc9bf375d7b...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/heapless/builds/299415471?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 612bf44a78c436db7d8aab83d0b65fc9bf375d7b to master...

**Pull request merged**
