### PR TITLE
impl Debug, PartialEq & Eq

### PR DESCRIPTION
**Pull request by japaric**
cc @fluffysquirrels

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0869d70 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0869d708775f102cfd2c0b461149ca9f4bfb91aa with merge 14977633c6e8d124296103e1f7bac9990ed0537b...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 63a6db3 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 63a6db397399a493bfb5045207c1d8f72a29d8a5 with merge eae8d06453e0c8f7256dec58f321f503c976996c...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/heapless/builds/319695536?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6d04705 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6d04705a118c95c5f813cc840b92a1e95b000849 with merge 72a79e683377b5be129c1d23f617c55f53303a79...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/heapless/builds/319698529?utm_source=github_status&utm_medium=notification)

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/heapless/builds/319698529?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 72a79e683377b5be129c1d23f617c55f53303a79 to master...

**Comment by fluffysquirrels** [comment]
Nice one.

**Pull request merged**
