### PR TITLE
use get_unchecked() instead of as_ptr().offset()

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 12d5019 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 12d501913e398da31dd348fae011206b78cce012 with merge f7ca3b5ec6c911e544d54fea9477c1d3ad62ee45...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/heapless/builds/295427299?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing f7ca3b5ec6c911e544d54fea9477c1d3ad62ee45 to master...

**Pull request merged**
