### PR TITLE
Implement retain for IndexSet/IndexMap.

### PR DESCRIPTION
**Pull request by jeandudey**
Needed to remove IndexMap/IndexSet elements while iterating over it.

### CODE REVIEW

**Comment by korken89** [comment]
Hi please rebase to fix tsan failure

**Comment by jeandudey** [comment]
@korken89 rebased

**Comment by korken89** [comment]
Hi, can you have a look at the failing tests?

Looks like you forgot to format the code.

**Comment by jeandudey** [comment]
Fixed the formatting

**Review by korken89 — APPROVED** [review]
bors merge

**Comment by korken89** [comment]
bors retry

**Comment by korken89** [comment]
bors retry

**Pull request merged**
