### PR TITLE
assume native compilation if target_os is not "none" to allow non-x86 hosts to run tests

### PR DESCRIPTION
**Pull request by TDHolmes**
I have an M1 Mac so the x86 specific test prevented me from running `cargo test`. I'm not sure why `scoped_threadpool` isn't just a plain old [`dev-dependency]` though... should I just make it an unqualified `[dev-dependency]` instead?

### CODE REVIEW

**Comment by TDHolmes** [comment]
@korken89 do you think this requires a CHANGELOG entry or is it too minor of a change?

**Comment by korken89** [comment]
Hi, all changes require a CHANGELOG entry.

**Comment by TDHolmes** [comment]
Wasn't sure if it was a "notable change" or not per the changelog header.
I'll add an entry

**Review by korken89 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
