### PR TITLE
Vec - PartialEq where Rhs is the Vec

### PR DESCRIPTION
**Pull request by elpiel**
I was using the Vec for tests and initially, I was confused because I saw the impl for PartialEq but then I realized that PartialEq with Rhs of Vec was not implemented.

These impls are not mandatory but might help other people when using Vec on Rhs.

PS: Amazing crate btw, thanks you for the awesome work!

### CODE REVIEW

**Review by japaric — APPROVED** [review]
awesome addition, thanks!

**Comment by elpiel** [comment]
Should I also add a Changelog entry because I see that the CI is failing?

**Comment by japaric** [comment]
> Should I also add a Changelog entry because I see that the CI is failing?

the changelog being missing is not a showstopper -- the CI check can be skipped. if you can update the changelog in this PR, that'd be great

**Comment by japaric** [comment]
v0.7.16 has been published and includes these changes

**Pull request merged**
