### PR TITLE
Add methods Vec::resize() and Vec::resize_default()

### PR DESCRIPTION
**Pull request by fluffysquirrels**
Semantics are the same as their equivalents in std::vec::Vec.

### CODE REVIEW

**Comment by japaric** [comment]
Thanks, @fluffysquirrels.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0917beb has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0917beb92a92d06f6267ee595a65cb0858f3ed59 with merge c644d4cf13f3a350a63674226e83b7d6b811f225...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/heapless/builds/319066660?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing c644d4cf13f3a350a63674226e83b7d6b811f225 to master...

**Comment by japaric** [comment]
v0.2.1 has been published

**Comment by fluffysquirrels** [comment]
Great, thanks!

**Pull request merged**
