### PR TITLE
Bump defmt from 0.2.1 to 0.3

### PR DESCRIPTION
**Pull request by henrikssn**

### CODE REVIEW

**Comment by korken89** [comment]
Hi, this is a breaking change - can 0.2 and 0.3 be implemented in parallel instead?

**Comment by henrikssn** [comment]
> Hi, this is a breaking change - can 0.2 and 0.3 be implemented in parallel instead?

I already checked the code in this repo and none of it is affected by the v0.3 changes. You can see them here: https://defmt.ferrous-systems.com/migration-02-03.html

**Comment by korken89** [comment]
Users of this library that are still using 0.2 would see breakage, hence it is a breaking change.

**Comment by henrikssn** [comment]
> Users of this library that are still using 0.2 would see breakage, hence it is a breaking change.

I'm not really sure how this could be achieved since dependencies can only be specified once IIUC (so we can't have a `defmt-03` feature in addition to the existing `defmt-impl` feature).

What would you propose?

**Comment by korken89** [comment]
One can rename the versions of the crate, e.g. `defmt` v0.2 as `defmt02` as described here: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#renaming-dependencies-in-cargotoml
This should work out fine.

**Comment by korken89** [comment]
I'm testing here: https://github.com/japaric/heapless/tree/dual-defmt
For some reason this does not work, but we use the same trick in `cortex-m-rtic` for multiple `cortex-m` dependencies: https://github.com/rtic-rs/cortex-m-rtic/blob/v0.5.x/Cargo.toml#L63

Not sure what's wrong...

**Comment by korken89** [comment]
I made a cargo issue, lets see what they say https://github.com/rust-lang/cargo/issues/10066

**Comment by korken89** [comment]
I think it is a `defmt` bug: https://github.com/knurling-rs/defmt/issues/625

**Comment by korken89** [comment]
In the end it's a `cargo` bug: https://github.com/rust-lang/cargo/issues/5969

**Comment by korken89** [comment]
We could say in the documentation that the `defmt-impl` flag enables the "latest" `defmt` release instead of a specific version.
This would allow us to update `defmt` in patch releases while it's still quite unstable.

**Comment by korken89** [comment]
Another idea that I lifted in the `defmt` issue, use a version range:

```toml
[dependencies.defmt]
version = ">=0.2,<0.4"
optional = true
```

Seems to work, but I'm not sure of unintended consequences.

**Comment by korken89** [comment]
I fixed a PR for the version range: https://github.com/japaric/heapless/pull/251

**Pull request closed without merging**
