### PR TITLE
add multiple-producer multiple-consumer lock-free queue

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by XOSplicer** [comment]
Hi, great addition to heapless. I just wonder: Is there a particular reason you implemented mpmc::Q* only for specific buffer sizes up to 64? Is there a way to make the implementation more generic?

**Comment by japaric** [comment]
> Is there a way to make the implementation more generic?

Not without losing the `const` constructors, AFAIK.

> Is there a particular reason you implemented mpmc::Q* only for specific buffer sizes up to 64?

No particular reason. If you need a larger capacity feel free to send a PR but note that the capacity needs to be a power of two (see code in the reference).

**Pull request merged**
