### PR TITLE
Implement core::fmt::Write for heapless::Vec<u8, N>

### PR DESCRIPTION
**Pull request by ijl**
I didn't see a mention of this in issues or previous pull requests, but I expect it's in scope?

### CODE REVIEW

**Comment by XOSplicer** [comment]
core::fmt::Write is implemented for heapless::String aswell, so I guess the implementation for Vec<u8> makes sense. String implements write_str() aswll as write_char(). Should both be implemented for Vec<u8> ?

**Comment by ijl** [comment]
I happened to only need this, and it's the only required part, but I could.

**Comment by korken89** [comment]
Hi could you add this for string as well?

**Comment by MathiasKoch** [comment]
@korken89 I think it is already implemented for String?

**Comment by korken89** [comment]
bors retry

**Pull request merged**
