### PR TITLE
add contention test

### PR DESCRIPTION
**Pull request by japaric**
This needs to be fixed before the next release

Interestingly I see that the test passes when compiled without optimizations but fails when
optimized. Perhaps there's some UB in here.

cc @pftbest

### CODE REVIEW

**Comment by pftbest** [comment]
What do you mean fails?

With a fix from https://github.com/japaric/heapless/issues/5#issuecomment-343178128 it passes for me in both debug and release.

**Comment by japaric** [comment]
> What do you mean fails?

Ahh, I opened this before seeing your patch as a sort of tracking issue for fixing this bug.

Thanks for the fix by the way 👍.

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ffcd423 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ffcd423e6765eb508d8ae7a305955428ddb7e573 with merge a885d6a47ef2947511ba8735e0062200c4b4c9b3...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/heapless/builds/299710155?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing a885d6a47ef2947511ba8735e0062200c4b4c9b3 to master...

**Pull request merged**
