### PR TITLE
Add HistoryBuffer::as_slices()

### PR DESCRIPTION
**Pull request by hulthe**
This method returns the contents of a HistoryBuffer as two ordered slices, similar to [Deque::as_slices()](https://docs.rs/heapless/0.7.16/heapless/struct.Deque.html#method.as_slices).

### CODE REVIEW

**Comment by korken89** [comment]
Hi, can you change so it uses a tuple instead?

**Comment by hulthe** [comment]
Sure can!

I personally think an array is more helpful though (e.g. like how i used into_iter in the test).
Though I could see an argument for keeping it more in line with similar functions, like Deque::as_slices.

**Comment by hulthe** [comment]
@korken89 here you go

**Review by korken89 — APPROVED** [review]
bors merge

**Review by korken89 — APPROVED** [review]
bors merge

**Review by korken89 — APPROVED** [review]
bors merge

**Pull request merged**
